# Generated by Django 4.1.1 on 2022-09-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BarcodeNumber', models.PositiveIntegerField(blank=True)),
                ('Image', models.ImageField(upload_to='')),
                ('WheightOfNewPackage', models.PositiveIntegerField()),
                ('WheightCurrentlyInStorage', models.PositiveIntegerField()),
                ('NumberOfItemsInNewPackage', models.PositiveIntegerField(default=1)),
                ('NumberOfItemsCurrentlyInStorage', models.PositiveIntegerField()),
            ],
        ),
    ]
